# 2025-07-21 09:00

name: Update XPTV JS Files

on:
#   workflow_dispatch:
 #  schedule:
  #   - cron: "0 */2 * * *"

permissions:
  actions: write
  contents: write

jobs:
  download-js:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: sooyaaabo/VOD-CMS-Widgets
        path: VOD-CMS-Widgets

    - name: Download JS files
      run: |
        mkdir -p VOD-CMS-Widgets/XPTV/JS
        declare -A jsfiles=(
          [91jav]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/91jav.js"
          [avdb]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/avdb.js"
          [avtoday]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/avtoday.js"
          [hanime]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/hanime.js"
          [hohoj]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/hohoj.js"
          [jable]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/jable.js"
          [javmove]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/javmove.js"
          [kanav]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/kanav.js"
          [kbjfan]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/kbjfan.js"
          [koreapornmovie]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/KoreaPornMovie.js"
          [missav]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/missav.js"
          [pandatv]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/pandatv.js"
          [pornhub]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/pornhub.js"
          [ppp]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/ppp.js"
          [supjav]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/SupJav.js"
          [taiav]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/taiav.js"
          [twivideo]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/twivideo.js"
          [xhamster]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/xhamster.js"
          [hdys]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/hdys.js"
          [madou]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/madou.js"
          [rou]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/rou.js"
          [taohuazu]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/taohuazu.js"
          [hkdoll]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/hkdoll.js"
          [uaa]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/uua.js"
          [harunasan]="https://gist.githubusercontent.com/Yswag/d9f072b75dab5b1b107c523dd148eea3/raw/harunasan.js"
          [4kav]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/4kav.js"
          [age]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/age.js"
          [anfuns]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/anfuns.js"
          [aowu]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/aowu.js"
          [catflix]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/catflix.js"
          [hdmoli]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/hdmoli.js"
          [libvio]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/libvio.js"
          [novipnoad]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/novipnoad.js"
          [iyftv]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/iyftv.js"
          [bdys]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/bdys.js"
          [czzy]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/czzy.js"
          [ddys]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/ddys.js"
          [duboku]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/duboku.js"
          [duanjutt]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/duanjutt.js"
          [gzys]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/gzys.js"
          [hjkk]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/hjkk.js"
          [bttwo]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/bttwo.js"
          [jpyy]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/jpyy.js"
          [jdys]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/jdys.js"
          [jcy]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/jcy.js"
          [laodifang]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/laodifang.js"
          [zero]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/zero.js"
          [ole]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/ole.js"
          [ppxys]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/ppxys.js"
          [saohuo]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/saohuo.js"
          [subaibai]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/subaibai.js"
          [tiantian]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/tiantian.js"
          [apple]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/apple.js"
          [xiaohys]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/xiaohys.js"
          [xingya]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/xingya.js"
          [ystt]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/ystt.js"
          [zxzj]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/zxzj.js"
          [sgsd]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/sgsd.js"
          [girigirilove]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/ai.js"
          [nmlive]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/nmlive.js"
          [bililive]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/bililive.js"
          [douyu]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/douyu.js"
          [huya]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/huya.js"
          [youtube]="https://gist.githubusercontent.com/Yswag/98b86b68755f698e2f601962f76c036a/raw/you.js"
          [alist_xiaoya]="https://raw.githubusercontent.com/kingreevice/my_xptv/main/js/alist_xiaoya.js"
          [alist_tvbox]="https://raw.githubusercontent.com/netcookies/xptv-extensions/main/alist_tvbox.js"
          [wobg]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/wobg.js"
          [aomi]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/aomi.js"
          [baipiao]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/baipiao.js" 
          [duoduo]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/yydsys.js"
          [guanying]="https://raw.githubusercontent.com/kingreevice/my_xptv/main/js/GYING_2025_2.js"
          [labipan]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/labipan.js"
          [leijing]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/leijing.js"
          [liuqu]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/liuqu.js"
          [muou]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/muou.js"
          [nanfeng]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/nanfdj.js"
          [ouge]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/ouge.js"
          [seedhub]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/seedhub.js"
          [shandian]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/shandian.js"
          [star2]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/star2.js"
          [texiafan]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/xiafan.js"
          [tgsearch]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/tgs_xp.js"
          [tianyiso]="https://gist.githubusercontent.com/occupy-pluto/874d9b180bcaff91e2dac06d38ed8474/raw/tianyiso.js"
          [wogg]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/wogg.js"
          [huban]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/huban.js"
          [mucpan]="https://raw.githubusercontent.com/kingreevice/my_xptv/main/js/mucpan.js"
          [xpanpan]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/xpanpan.js"
          [xzys]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/xzys.js"
          [yunchao]="https://raw.githubusercontent.com/kingreevice/my_xptv/main/js/yunchao.js"
          [yunpan8]="https://raw.githubusercontent.com/fangkuia/XPTV/main/js/yunpan8.js"
          [yunpanres]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/yunpanres.js"
          [mihdr]="https://raw.githubusercontent.com/Yswag/xptv-extensions/main/js/mihdr.js"
        )
        
        for js_name in "${!jsfiles[@]}"; do
          url="${jsfiles[$js_name]}"
          curl -A -L -o "VOD-CMS-Widgets/XPTV/JS/${js_name}.js" "$url"
          sed -i "1s|^|// 引用链接: $url\n|" "VOD-CMS-Widgets/XPTV/JS/$js_name.js"
        done

    - name: Commit and push changes
      working-directory: VOD-CMS-Widgets
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add XPTV/JS/
        git commit -m "Synchronously Update JS files" || echo "No changes to commit"
        git push
        
    - name: Clear Workflow
      uses: Mattraks/delete-workflow-runs@main
      with:
        retain_days: 0
        keep_minimum_runs: 12
